name: issue-tracking

services:
  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    env_file:
      - ./env/db.env
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    restart: always
    healthcheck:
      test: ["CMD","redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  server:
    build: .
    ports:
      - "3000:3000"
      - "3001:3001"
    env_file:
      - env/server.env
    depends_on:
      redis:
        condition: service_healthy
      mariadb:
        condition: service_healthy

volumes:
  mariadb_data:
  redis_data: